def display_main_menu():
    print("\n" + "=" * 50)
    print("     Personal Finance Manager")
    print("=" * 50)
    print("1.Transactions")
    print("2.Reports")
    print("3.Search")
    print("4.Categories")
    print("5.Settings")
    print("6.Exit")